# Generated by Django 3.2.8 on 2021-11-12 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_auto_20211112_0831'),
        ('judge', '0002_auto_20211112_0853'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Problem_test_case',
            new_name='Testcase',
        ),
    ]
