# Generated by Django 3.2.8 on 2021-11-12 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0004_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='runtime',
            field=models.IntegerField(default=0),
        ),
    ]
