# Generated by Django 3.2.8 on 2021-11-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judge', '0005_alter_submission_runtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='language',
            field=models.CharField(default='C++', max_length=10),
        ),
    ]
