# Generated by Django 3.2.8 on 2021-10-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_profile_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_img',
        ),
    ]
