# Generated by Django 3.2.8 on 2021-10-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_profile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last10stat',
            field=models.CharField(default='----------', max_length=10),
        ),
    ]
