# Generated by Django 3.2.8 on 2021-10-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_profile_last10stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_match',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_raito',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_win',
            field=models.BigIntegerField(default=0),
        ),
    ]
