# Generated by Django 3.2.8 on 2021-10-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211020_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_problems',
            field=models.IntegerField(default=0),
        ),
    ]
