# Generated by Django 3.2.8 on 2021-10-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_profile_total_problems'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='color',
            field=models.CharField(default='grey', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(default='Level 1', max_length=15),
        ),
    ]
