# Generated by Django 3.2.8 on 2021-10-20 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_problem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
