# Generated by Django 3.2.8 on 2021-10-20 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_problem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
