# Generated by Django 3.2.8 on 2021-10-21 01:39

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_problem'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='description',
            field=martor.models.MartorField(default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='tag',
            field=models.CharField(choices=[('800+', '800+'), ('900+', '900+'), ('1000+', '1000+'), ('1100+', '1100+'), ('1200+', '1200+'), ('1300+', '1300+'), ('1400+', '1400+'), ('1500+', '1500+'), ('1600+', '1600+'), ('1700+', '1700+'), ('1800+', '1800+'), ('1900+', '1900+'), ('2000+', '2000+'), ('2100+', '2100+'), ('2200+', '2200+'), ('2300+', '2300+'), ('2400+', '2400+'), ('2500+', '2500+'), ('2600+', '2600+'), ('2700+', '2700+'), ('2800+', '2800+'), ('2900+', '2900+')], default='?', max_length=6),
        ),
        migrations.AddField(
            model_name='problem',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
