# Generated by Django 3.2.8 on 2021-10-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_problem_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='accepted_user',
            field=models.IntegerField(default=0),
        ),
    ]
