# Generated by Django 3.2.8 on 2021-10-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_problem_time_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='description',
        ),
        migrations.AddField(
            model_name='problem',
            name='statement',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
