# Generated by Django 3.2.8 on 2021-10-27 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20211027_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='memory_limit',
            field=models.IntegerField(default=64),
        ),
    ]
