# Generated by Django 3.2.8 on 2021-10-28 03:15

from django.db import migrations, models
import django.utils.timezone
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_problem_memory_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=martor.models.MartorField(default=''),
        ),
        migrations.AddField(
            model_name='blog',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
