# Generated by Django 3.2.8 on 2021-10-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20211028_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
