# Generated by Django 3.2.8 on 2021-10-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_blog_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='viewed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
