# Generated by Django 3.2.8 on 2021-10-29 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_blog_vote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_id',
        ),
        migrations.AlterField(
            model_name='blog',
            name='entry_id',
            field=models.CharField(default='', max_length=50, primary_key=True, serialize=False),
        ),
    ]
