# Generated by Django 3.2.8 on 2021-11-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20211029_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='on_feed',
            field=models.BooleanField(default=False),
        ),
    ]
