# Generated by Django 3.2.8 on 2021-11-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_blog_on_feed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_diff',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.CharField(default='', max_length=20000),
        ),
    ]
