# Generated by Django 3.2.8 on 2021-11-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_rename_total_raito_profile_total_ratio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_diff',
            field=models.TextField(default='0.00', max_length=8),
        ),
    ]
