# Generated by Django 3.2.8 on 2021-11-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_alter_profile_total_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_diff',
            field=models.CharField(default='0.00', max_length=8),
        ),
    ]
