# Generated by Django 3.2.8 on 2021-11-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_alter_profile_total_diff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(default='', max_length=20000),
        ),
    ]
