# Generated by Django 3.2.8 on 2021-11-09 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
