# Generated by Django 3.2.8 on 2021-11-10 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20211110_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slogan',
            field=models.CharField(default='', max_length=50),
        ),
    ]
