# Generated by Django 3.2.8 on 2021-11-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_auto_20211112_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solve_function_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='problem',
            name='solve_function_arg',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
