# Generated by Django 3.2.8 on 2021-11-12 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_auto_20211112_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='solve_function_arg',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='solve_function_type',
        ),
    ]
